### ISSUE TITLE
[Bug] Executing command via @ping doesn't work

### ISSUE THREAD

**Issue by Hotvinyl6347** [Hotvinyl6347/rem-rin-bot-issues#1]
**Describe the bug**
Can't perform bot commands by using ping

**Steps to reproduce**
1. Do a command but instead of prefix use @mention

**Expected behavior**
Should execute cmd

**Actual behavior**
Doesn't respond

**Screenshots**

**Rem-rin Version Type**
Nightly

**Comment by Hotvinyl6347** [comment]
balls

**Comment by GizmoTjaz** [comment]
**cock and ball torture**

**Comment by Hotvinyl6347** [comment]
fixed
